"""Initial migration

Revision ID: 32d5227bfa03
Revises: 1eaf77d84b00
Create Date: 2023-11-09 00:47:51.376777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32d5227bfa03'
down_revision: Union[str, None] = '1eaf77d84b00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('description', sa.String(), nullable=True))
    op.add_column('rooms', sa.Column('quantity', sa.Integer(), nullable=False))
    op.drop_column('rooms', 'quatity')
    op.drop_column('rooms', 'descriptions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('descriptions', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('rooms', sa.Column('quatity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('rooms', 'quantity')
    op.drop_column('rooms', 'description')
    # ### end Alembic commands ###
