"""Initial migration

Revision ID: 6c866899ba2c
Revises: c266dac92434
Create Date: 2023-11-09 02:44:21.041366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c866899ba2c'
down_revision: Union[str, None] = 'c266dac92434'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'services')
    op.drop_column('rooms', 'image_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('rooms', sa.Column('services', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
