"""Initial migration

Revision ID: 967f0bad4627
Revises: b28e5f86bc52
Create Date: 2023-11-09 02:38:15.263694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '967f0bad4627'
down_revision: Union[str, None] = 'b28e5f86bc52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('hotel_id', sa.Integer(), nullable=False))
    op.add_column('rooms', sa.Column('name', sa.String(), nullable=False))
    op.add_column('rooms', sa.Column('description', sa.String(), nullable=True))
    op.add_column('rooms', sa.Column('price', sa.Integer(), nullable=False))
    op.add_column('rooms', sa.Column('services', sa.JSON(), nullable=True))
    op.add_column('rooms', sa.Column('quantity', sa.Integer(), nullable=False))
    op.add_column('rooms', sa.Column('image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rooms', 'hotels', ['hotel_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.drop_column('rooms', 'image_id')
    op.drop_column('rooms', 'quantity')
    op.drop_column('rooms', 'services')
    op.drop_column('rooms', 'price')
    op.drop_column('rooms', 'description')
    op.drop_column('rooms', 'name')
    op.drop_column('rooms', 'hotel_id')
    # ### end Alembic commands ###
