"""Initial migration

Revision ID: b28e5f86bc52
Revises: 673b389a9422
Create Date: 2023-11-09 02:37:05.812232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b28e5f86bc52'
down_revision: Union[str, None] = '673b389a9422'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('rooms_hotel_id_fkey', 'rooms', type_='foreignkey')
    op.drop_column('rooms', 'services')
    op.drop_column('rooms', 'price')
    op.drop_column('rooms', 'test')
    op.drop_column('rooms', 'image_id')
    op.drop_column('rooms', 'name')
    op.drop_column('rooms', 'quantity')
    op.drop_column('rooms', 'hotel_id')
    op.drop_column('rooms', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('rooms', sa.Column('hotel_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('rooms', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('rooms', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('rooms', sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('rooms', sa.Column('test', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('rooms', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('rooms', sa.Column('services', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_foreign_key('rooms_hotel_id_fkey', 'rooms', 'hotels', ['hotel_id'], ['id'])
    # ### end Alembic commands ###
